-
  id: 1
  title: Jab Jab Jab, Right Hook
  price: 2000
  photo: gary-vaynerchuk-jab-jab-jab
-
  id: 2
  title: Intercom on Starting Up
  price: 1250
  photo: intercom-starting-up
-
  id: 3
  title: Lean Startup
  price: 1750
  photo: lean-startup
